### ISSUE TITLE
Python-Bluez nicht installierbar

### ISSUE THREAD

**Issue by pekae** [red-ip/spot#1]
Ich versuche Python-bluez zu installieren und bekomme die Meldung, dass Python-Bluez nicht gefunden wird

starte ich Spot, bekomme ich die Meldung, dass die bluetooth Verbindung zu Python nicht installiert sei

was mache ich falsch ?

**Comment by red-ip** [comment]
Auf einem Ubuntu System solltest Du die folgenden Sachen installiert haben:
```
apt-get install python{,3}-pip 
apt-get install bluetooth python-bluez git
```

Denk auch dran mit "bluetoothctl" das Bluetooth pairing durchzuführen. Melde dich bei weiteren Fragen.

**Comment by pekae** [comment]
Danke für die Antwort 

Ich bekomme immer die Meldung, dass es Python-bluez nicht gibt

Ich habe einen 2ten Sensor
Wie muss der Aufruf des Masters sein, um den 2ten zu erkennen?

-m ….,.


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Alles Gute zum Neuen Jahr 

Habe nun die Installation des 2ten Sensor geschafft ( neue Source in die Liste eingetragen und bluetooth-bluez installiert)

Ich starte den Sensor mit spot_sensor.py - fehlerfrei

Wenn dieser gestartet ist, funktioniert die Erkennung nicht mehr. 
Schalte ich den 2ten Sensor aus, erkennt der 1te einwandfrei mein Handy (an und aus) - mit 2tem Sensor steht die Homematic Variable immer aus false 

Wie kann ich erkennen wo das Problem liegt und welcher Sensor was meldet ?


Mit freundlichen Gruß

Peter Kästner

**Comment by red-ip** [comment]
Auch Dir alles Gute zum Neuen Jahr.

Wenn ich es richtig verstanden habe, hast Du zwei pi's (raspberry pi's). 
Dann solltest Du auf den ersten pi es folgendermassen starten:
`sudo python /opt/spot/spot.py -d`
Der "Sensor" startet hiermit automatisch mit.

auf dem zweiten pi:
`sudo python /opt/spot/spot_sensor.py -d`

Das Bluetooth pairing mit den zu prüfenden Gerät (Telefon) muss dann auch auf beiden pi's gemacht werden.  
Damit prüfen beide pi's die Geräte ab aber nur der erste kommuniziert mit der Homematic.

**Comment by red-ip** [comment]
Der Master sucht die Sensoren im Netzwerk automatisch. Du kannst die Start-Parameter (Spot / Sensor) mit den folgenden Aufruf Dir anzeigen lassen: 
`sudo python /opt/spot/spot.py -h`
`sudo python /opt/spot/spot_sensor.py -h`
Hier siehst Du auch wie Du alles im DEBUG Modus kannst um zu sehen was im Hintergrund alles passiert.

**Comment by red-ip** [comment]
`tail -f -n 50 /opt/spot/log/spot_check.log`
oder 
`tail -f -n 50 /opt/spot/log/spot_sensor.log`
immer meine erste Anlaufstelle um zu sehen ob alles korrekt funktioniert. 

Beim Sensor solltest Du etwas wie das hier angezeigt bekommen:
_17.12.2021 21:45:36 [INFO    ] Load Config file.. /opt/spot/spot.cfg
17.12.2021 21:45:36 [INFO    ] Preparing to run in daemon mode
17.12.2021 21:45:36 [INFO    ] Local Hostname is : pi2
17.12.2021 21:45:36 [INFO    ] Bind the socket to the IP:Port : 192.168.110.4:10002_

Beim Spot solltest Du etwas wie das hier angezeigt bekommen:
_01.01.2022 20:55:48 [INFO    ] Load Config file.. /opt/spot/spot.cfg
01.01.2022 20:55:48 [INFO    ] Preparing to run in daemon mode
01.01.2022 20:55:50 [INFO    ] Starting to collect parameters
01.01.2022 20:55:52 [INFO    ] Connection to the CCU establish (RX): 192.168.110.2
01.01.2022 20:55:52 [INFO    ] All parameters collected. System OK -> STARTING WORK
01.01.2022 20:56:08 [ERROR   ] Sensor 192.168.110.5 timeout - sensor_com.py - get_sensor_name
01.01.2022 20:56:08 [INFO    ] Sensor :192.168.110.5 (unknown) is online
01.01.2022 20:56:14 [ERROR   ] Sensor 192.168.110.4 timeout - sensor_com.py - get_sensor_name
01.01.2022 20:56:14 [INFO    ] Sensor :192.168.110.4 (unknown) is online
01.01.2022 20:56:15 [INFO    ] Sensor :192.168.110.200 (pi3) is online_

(Die beiden ERROR sind nur Kosmetik und haben keinen Einfluss auf die Funktion.)

**Comment by pekae** [comment]
Hi
Dankeschön für die Antwort 

Genau so habe ich es gemacht

Läuft nur der erste (Master) erkennt er das Handy und setzt die Variable

Starte ich den 2ten (als Sensor wie oben beschrieben) , steht die Variable immer auf false - der 2te übertrumpft also den Master obwohl ich in unmittelbarer Nähe zum 2ten bin - normalerweise müsste die Variable doch True sein, wenn einer der beiden Sensoren das Handy erkennt 


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Wer ist 
.4 
.5
.200
Im Beispiel?


Mit freundlichen Gruß

Peter Kästner

**Comment by red-ip** [comment]
Absolut richtig, der Master sammelt und akkumuliert erst die Daten aller Sensoren und dann setzte er die Variable in der CCU. 
In meinen Beispiel sind .4, .5 und .200 Sensoren. Der Master läuft mit auf der .4

Kannst Du die Logs von allen raspberry's mal posten?

hier den Befehl:
```
tail -n 30 /opt/spot/log/spot_check.log
tail -n 20 /opt/spot/log/spot_sensor.log

```

**Comment by pekae** [comment]
Anbei die Logs

Denke er findet den Sensor/Master nicht


Mit freundlichen Gruß

Peter Kästner

Anfang der weitergeleiteten Nachricht:

> Von: Peter Kaestner ***@***.***>
> Datum: 2. Januar 2022 um 19:36:52 MEZ
> An: Peter ***@***.***>
> Betreff: AW: [red-ip/spot] Python-Bluez nicht installierbar (Issue #1)
> 
> ﻿
>  
>  
> Mit freundlichem Gruß
>  
> Peter Kästner
>  
> Von: Peter
> Gesendet: Sonntag, 2. Januar 2022 19:21
> An: Peter Kaestner
> Betreff: Fwd: [red-ip/spot] Python-Bluez nicht installierbar (Issue #1)
>  
>  
> 
>  
> Mit freundlichen Gruß
>  
> Peter Kästner
> 
> Anfang der weitergeleiteten Nachricht:
> 
> Von: red-ip ***@***.***>
> Datum: 2. Januar 2022 um 13:03:23 MEZ
> An: red-ip/spot ***@***.***>
> Kopie: pekae ***@***.***>, Author ***@***.***>
> Betreff: Aw: [red-ip/spot] Python-Bluez nicht installierbar (Issue #1)
> Antwort an: red-ip/spot ***@***.***>
> 
> ﻿
> Absolut richtig, der Master sammelt und akkumuliert erst die Daten aller Sensoren und dann setzte er die Variable in der CCU.
> In meinen Beispiel sind .4, .5 und .200 Sensoren. Der Master läuft mit auf der .4
> 
> Kannst Du die Logs von allen raspberry's mal posten?
> 
> hier den Befehl:
> 
> tail -n 30 /opt/spot/log/spot_check.log
> tail -n 20 /opt/spot/log/spot_sensor.log
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
>  

Master mit Sensor 10.221.223.123:

***@***.***:/opt/spot/log# tail -n 30 /opt/spot/log/spot_check.log
02.01.2022 01:59:40 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 01:59:44 [INFO    ] Sensor : None . Disconnected
02.01.2022 01:59:45 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 01:59:46 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 01:59:49 [INFO    ] Sensor : None . Disconnected
02.01.2022 01:59:50 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 01:59:51 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 01:59:54 [INFO    ] Sensor : None . Disconnected
02.01.2022 01:59:55 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 01:59:56 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 02:00:00 [INFO    ] Sensor : None . Disconnected
02.01.2022 02:00:01 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 02:00:02 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 02:00:05 [INFO    ] Sensor : None . Disconnected
02.01.2022 02:00:06 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 02:00:07 [ERROR   ] Sensor None timeout - sensor_com.py - display_rgbled
02.01.2022 02:00:11 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 02:00:11 [INFO    ] Sensor : None . Disconnected
02.01.2022 02:00:12 [ERROR   ] Sensor None timeout - sensor_com.py - display_msg
02.01.2022 02:00:19 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 02:00:19 [INFO    ] Preparing to run in daemon mode
02.01.2022 02:00:21 [INFO    ] Starting to collect parameters
02.01.2022 02:00:26 [INFO    ] Connection to the CCU establish (RX): 10.221.223.151
02.01.2022 02:00:27 [INFO    ] All parameters collected. System OK -> STARTING WORK
02.01.2022 19:22:49 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:22:58 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:22:58 [INFO    ] Preparing to run in daemon mode
02.01.2022 19:22:59 [INFO    ] Starting to collect parameters
02.01.2022 19:23:03 [INFO    ] Connection to the CCU establish (RX): 10.221.223.151
02.01.2022 19:23:04 [INFO    ] All parameters collected. System OK -> STARTING WORK
***@***.***:/opt/spot/log# tail -n 20 /opt/spot/log/spot_sensor.log
02.01.2022 18:22:26 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:22:26 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:32:27 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:32:27 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:42:28 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:42:28 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:52:30 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 18:52:30 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:02:31 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:02:31 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:12:32 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:12:32 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:22:33 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:22:33 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
02.01.2022 19:22:50 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:22:58 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:22:59 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:22:59 [INFO    ] Preparing to run in daemon mode
02.01.2022 19:23:03 [INFO    ] Local Hostname is : raspberrypi
02.01.2022 19:23:03 [INFO    ] Bind the socket to the IP:Port : 10.221.223.123:10002
***@***.***:/opt/spot/log#

Slave - 2ter Sensor - 10.221.223.143

***@***.***:/opt/spot/log# tail -n 30 /opt/spot/log/spot_check.log
tail: '/opt/spot/log/spot_check.log' kann nicht zum Lesen geöffnet werden: Datei oder Verzeichnis nicht gefunden
***@***.***:/opt/spot/log# tail -n 20 /opt/spot/log/spot_sensor.log
02.01.2022 15:29:58 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 15:29:58 [INFO    ] Preparing to run in daemon mode
02.01.2022 15:30:09 [INFO    ] Local Hostname is : PiZero
02.01.2022 15:30:09 [INFO    ] Bind the socket to the IP:Port : 169.254.11.90:10002   
.
***@***.***:/opt/spot/log# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 30  bytes 2912 (2.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 30  bytes 2912 (2.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.221.223.143  netmask 255.255.255.0  broadcast 10.221.223.255
        inet6 2a00:6020:b39f:2856:ff1e:4208:912f:954d  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::6f4f:77cc:df3a:c305  prefixlen 64  scopeid 0x20<link>

        ether e4:5f:01:56:93:25  txqueuelen 1000  (Ethernet)
        RX packets 2144  bytes 480071 (468.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 189  bytes 32208 (31.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

***@***.***:/opt/spot/log#


***@***.***:/opt/spot/log# cat *
02.01.2022 15:29:58 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 15:29:58 [INFO    ] Preparing to run in daemon mode
02.01.2022 15:30:09 [INFO    ] Local Hostname is : PiZero
02.01.2022 15:30:09 [INFO    ] Bind the socket to the IP:Port : 169.254.11.90:10     <<<<<<<<<<<< - ip unbekannt 

neu gestartet :
                                                                                                      002
02.01.2022 19:28:57 [INFO    ] Load Config file.. /opt/spot/spot.cfg
02.01.2022 19:28:57 [INFO    ] Preparing to run in daemon mode
02.01.2022 19:29:16 [INFO    ] Local Hostname is : PiZero
02.01.2022 19:29:16 [INFO    ] Bind the socket to the IP:Port : 10.221.223.143:1                                                                                                      0002

**Comment by red-ip** [comment]
Mich wundert das der pi zero eine APIPA bindet. Bitte lese den folgenden Artikel durch und prüfe ob das bei dir hinkommt.

https://www.elektronik-kompendium.de/sites/raspberry-pi/2010011.htm

**Comment by pekae** [comment]
Deswegen hatte ich rebootet , dann hatte er auf die lokale ip des 2ten Sensor gebunden 

Hatte aber keine Auswirkung- funktioniert trotzdem nicht


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Habe auf feste ip umgestellt- ändert nichts

Die Variable auf der ccu wurde gestern Nachmittag das letzte Mal geändert 


Mit freundlichen Gruß

Peter Kästner

**Comment by red-ip** [comment]
Versuch mal bitte das folgende: 
beende auf den beiden pi's die spot Prozesse:
Master:
```
sudo python /opt/spot/spot.py -s
sudo python /opt/spot/spot_sensor.py -s
```
Sensor:
`sudo python /opt/spot/spot_sensor.py -s`

du kannst mit `ps aux | grep spot | grep -v grep` zusätzlich prüfen ob alle Prozesse beendet wurden. Falls nicht kannst Du mit `sudo kill` und der prozess id kannst Du es manuell machen.

Dann starten wir alles in debug modus. (Reihenfolge ist wichtig)
erst den Sensor:
`sudo python /opt/spot/spot_sensor.py -d`

dann der Master:
`sudo python /opt/spot/spot_sensor.py -d`
`sudo python /opt/spot/spot.py -n -l`

Dann warten 1Min. Mich interessiert die Terminal Ausgabe von den Master. Schieck mir die bitte und auch die Logs.

**Comment by pekae** [comment]
Dankeschön für deine Mühe 




Mit freundlichen Gruß

Peter Kästner

> Am 04.01.2022 um 09:15 schrieb red-ip ***@***.***>:
> 
> ﻿
> Versuch mal bitte das folgende:
> beende auf den beiden pi's die spot Prozesse:
> Master:
> 
> sudo python /opt/spot/spot.py -s
> sudo python /opt/spot/spot_sensor.py -s
> Sensor:
> sudo python /opt/spot/spot_sensor.py -s
> 
> du kannst mit ps aux | grep spot | grep -v grep zusätzlich prüfen ob alle Prozesse beendet wurden. Falls nicht kannst Du mit sudo kill und der prozess id kannst Du es manuell machen.
> 
> Dann starten wir alles in debug modus. (Reihenfolge ist wichtig)
> erst den Sensor:
> sudo python /opt/spot/spot_sensor.py -d
> 
> dann der Master:
> sudo python /opt/spot/spot_sensor.py -d
> sudo python /opt/spot/spot.py -n -l
> 
> Dann warten 1Min. Mich interessiert die Terminal Ausgabe von den Master. Schieck mir die bitte und auch die Logs.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

2ter Sensor 10.221.223.222:

***@***.***:/opt/spot# 




sudo python /opt/spot/spot_sensor.py -d
info     Load Config file.. /opt/spot/spot.cfg
------------------- spot_sensore 1.6.6 -------------------
---------- Sensor name : PiZero ----------
------------------- Preparing to run in daemon mode -------------------
info     Preparing to run in daemon mode

started with pid 6642
***@***.***:/opt/spot#

***@***.***:/opt/spot# ps aux | grep spot | grep -v grep
root      6642  0.0  1.6  26272  7240 ?        Sl   10:34   0:00 python /opt/spot/spot_sensor.py -d



Master 10.221.223.123:

***@***.***:/opt/spot# sudo python  /opt/spot/spot.py -n -l
info     Load Config file.. /opt/spot/spot.cfg
------------------- Spot 1.7.0 -------------------
------------------- Log DEBUG manual set to True -------------------
debug    DEBUG LOG manual set to True
Terminal Mode
info     Starting to collect parameters
debug    checking if ip interface is ready
debug    IP interface is ready to go! local IP : 10.221.223.123
debug    Running Auto Discovery for Sensors
debug    sending broadcast to discover the sensors
debug    1 sensors discovered : {'10.221.223.123': '10002 '}
debug    Getting Devices for check from CCU2
debug    Connecting to the CCU to get device list : 10.221.223.151
info     Connection to the CCU establish (RX): 10.221.223.151
info     All parameters collected. System OK -> STARTING WORK
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Sensor 10.221.223.123 replied with raspberrypi to gethostname
info     Sensor :10.221.223.123 (raspberrypi) is online
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    sendVariableToCCU2 Command : http://10.221.223.151/config/xmlapi/statechange.cgi?ise_id=51984&new_value=true
debug    sendVariableToCCU2.html Answer from CCU2 : <?xml version="1.0" encoding="ISO-8859-1" ?><result><changed id="51984" new_value="true" /></result>
info      IN - peters since 2022-01-04-10:36:22. Seen by : 10.221.223.123

debug    44:F2:1B:17:CD:E4 - peters is here now. Update is sent to CCU2
debug    44:F2:1B:17:CD:E4 changes successfully updated to CCU2
debug    10.221.223.123 sending msg to sensor's display : I:peters
debug    Sensor 10.221.223.123 has not displayed Text: I:peters
debug    10.221.223.123 sending rgb LED to sensor's LED : 001
debug    Sensor 10.221.223.123 has not show RGB LED: 001
debug    1 of 1 are in the coverage of Spot
debug    1 devices around
debug    10.221.223.123 sending rgb LED to sensor's LED : 010
debug    Sensor 10.221.223.123 has not show RGB LED: 010
debug    going sleep for 40.0 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 is first time no seen. Loop : 4
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    sendVariableToCCU2 Command : http://10.221.223.151/config/xmlapi/statechange.cgi?ise_id=51984&new_value=false
debug    sendVariableToCCU2.html Answer from CCU2 : <?xml version="1.0" encoding="ISO-8859-1" ?><result><changed id="51984" new_value="false" /></result>
info     OUT - peters since 2022-01-04-10:37:16.
debug    44:F2:1B:17:CD:E4 - peters is last seen at 2022-01-04-10:37:16. going to update the CCU2
debug    44:F2:1B:17:CD:E4 changes successfully updated to CCU2
debug    10.221.223.123 sending msg to sensor's display : O:peters
debug    Sensor 10.221.223.123 has not displayed Text: O:peters
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors

debug    44:F2:1B:17:CD:E4 remains unavailable
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    10.221.223.123 sending rgb LED to sensor's LED : 100
debug    Sensor 10.221.223.123 has not show RGB LED: 100
debug    going sleep for 1 s
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor

**Comment by red-ip** [comment]
Hallo Peter,
dein Sensor mit der "10.221.223.222" wird nicht erkannt. Hier kann es ein paar Gründe geben. Kannst Du mal auf deinem WLAN Access Point nach eine Funktion suchen die Broadcast-Filterung / Broadcast-zu Unicast macht und diese Testweise abschalten. 

Ein anderes Problem was dich eventuell später erwartet wird ist, der PiZero W ist sehr schlecht darin WLAN und BT gleichzeitig zu machen (weil nur ein chip). Ich musste bei mir einen zusätzlichen WLAN Adapter verwenden für einen stabile WLAN Verbindung wenn ich über bluetooth die Abfragen mache. Das scheint ein generelles Problem zu sein. Man kann dazu viel in Netz lesen. Aber das nur nebenbei und nicht für das "nicht erkennen des zweiten Sensors" verantwortlich.

Wir können uns auch mal für eine Remote Session verabreden wenn Du nicht weiter kommst. Ich weiss nur nicht wie

**Comment by pekae** [comment]
Hi
Wifi geändert - nun erkennt er den Sensor
Geht aber noch nicht, da ich jetzt anscheinend das genannte Zero Problem habe
Muss mir wifistick gediegen

Melde mich wieder

Herzlichen Dank für deine Mühe 


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Moin

Hab mal nen wlan Stick dran - nix geändert 

Ich denke es ist ein anderes Problem 

Starte ich den Spot-Sensor manuell (über ssh) 
Entweder über Python spot_sensor.py -d
Oder in init.d über ./Spot Start

Funktioniert alles

Mache ich reboot und Spot startet automatisch geht es nicht

Logfile :  

log vom Master - 2ter Sensor wurde nach reboot automatisch über init.d gestart
 
 
er findet den 2ten Sensor nicht richtig - none - 10002
 
going sleep for 1 s
debug    Rediscovering Sensor and devices. Loop : 16
debug    Connecting to the CCU to get device list : 10.221.223.151
debug    sending broadcast to discover the sensors
debug    2 sensors discovered : {'None': '10002 ', '10.221.223.123': '10002 '}
debug    checking if : None . ready to receive the device list
debug    Sensor ping failed to : None . Moving on to the next sensor
info     Sensor : None . Disconnected
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
debug    Beginning to calculate the presence information from the Sensors
debug    44:F2:1B:17:CD:E4 is first time no seen. Loop : 16
debug    0 of 1 are in the coverage of Spot
debug    no more devices around
debug    None sending msg to sensor's display : ALL OUT
error    Sensor None timeout - sensor_com.py - display_msg
debug    10.221.223.123 sending msg to sensor's display : ALL OUT
debug    Sensor 10.221.223.123 has not displayed Text: ALL OUT
debug    None sending rgb LED to sensor's LED : 100
 
 
2ter sensor manuell gestartet 
 
python spot_sensor.py -d
 
oder über init.d manuell ./spot start
 
nun findet er den Sensor mit der richtigen IP (statt none) und dem Port - manchmal zeigt er statt der IP  auch den Hostnamen - alles ok
 
debug    checking if ip interface is ready
debug    IP interface is ready to go! local IP : 10.221.223.123
debug    Running Auto Discovery for Sensors
debug    sending broadcast to discover the sensors
debug    2 sensors discovered : {'10.221.223.222': '10002 ', '10.221.223.123': '10002 '}
debug    Getting Devices for check from CCU2
debug    Connecting to the CCU to get device list : 10.221.223.151
info     Connection to the CCU establish (RX): 10.221.223.151
info     All parameters collected. System OK -> STARTING WORK
debug    checking if : 10.221.223.222 . ready to receive the device list
debug    10.221.223.222. Sensor is waiting for Data..
debug    10.221.223.222 sending data to Sensor
error    Sensor 10.221.223.222 timeout - sensor_com.py - get_sensor_name
info     Sensor :10.221.223.222 (unknown) is online
debug    Sensor 10.221.223.123 replied with raspberrypi to gethostname
info     Sensor :10.221.223.123 (raspberrypi) is online
debug    checking if : 10.221.223.123 . ready to receive the device list
debug    10.221.223.123. Sensor is waiting for Data..
debug    10.221.223.123 sending data to Sensor
 


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Hi

So, jetzt gehts


Hab nochmals den autostart gelöscht, neu eingetragen, Rechte und User gesetzt - jetzt geht auch, wenn ich reboote

Den wlan-Stick habe ich auf mal weg - geht trotzdem fehlerfrei 

Herzlichen Dank für deine Mühe und das tolle Programm 


Mit freundlichen Gruß

Peter Kästner

**Comment by red-ip** [comment]
Moin Peter,

es freut mich zu hören das es jetzt funktioniert.

VG
Marius
